
conector_final = sorted(['a fim de', 'a fim de que', 'a propósito', 'através',
                       'com o intuito de', 'com o objetivo de', 'para',
                       'para esse fim', 'para isso', 'para que', 'para tanto'], reverse=True)

conector_causal = sorted(['assim', 'causado por', 'com isso', 'como consequência',
                        'como resultado', 'consequentemente', 'dado que',
                        'dessa forma', 'dessa maneira', 'desse modo', 'diante disso',
                        'em resposta', 'já que', 'logo', 'nesse caso', 'pois', 'pois que',
                        'por causa', 'por causa que', 'por conseguinte', 'por essa razão',
                        'por esse motivo', 'por isso', 'por isso que', 'por quanto', 'porque',
                        'portanto', 'sendo assim', 'tanto mais que',
                        'uma vez que', 'visto como', 'visto que'], reverse=True)

# important
verbo_causa = sorted(['acarretar', 'afetar', 'ajudar', 'arriscar', 'atingir',
                    'ativar', 'aumentar', 'auxiliar', 'avivar', 'capacitar',
                    'captar', 'causar', 'cessar', 'condicionar',
                    'confundir', 'contribuir', 'criar', 'danificar',
                    'dar', 'deixar', 'derrubar', 'descontinuar', 'desencadear',
                    'desistir', 'destruir', 'determinar', 'devastar', 'dificultar',
                    'dispensar', 'disponibilizar', 'efetuar', 'engendrar', 'ensinar',
                    'estimular', 'facilitar', 'fazer', 'finalizar', 'fomentar',
                    'fornecer', 'garantir', 'gerar', 'impor', 'impossibilitar',
                    'instigar', 'irritar', 'levar', 'melhorar', 'motivar', 'mudar',
                    'obter', 'ocasionar', 'originar', 'perder', 'permitir',
                    'possibilitar', 'preocupar', 'preservar', 'produzir',
                    'programar', 'promover', 'propiciar', 'proporcionar',
                    'provocar', 'puxar', 'reduzir', 'resultar', 'servir', 'solucionar',
                    'subsidiar', 'suprir', 'surgir', 'suscitar',
                    'tornar', 'trazer', 'viabilizar', 'visar'], reverse=True)

action_verbs = sorted(['votar', 'voltar', 'voar', 'viver', 'visitar', 'visar',
                    'virar', 'vir', 'viabilizar', 'vestir', 'verificar', 'ver',
                    'vencer', 'variar', 'valer', 'utilizar', 'usar', 'unir',
                    'trocar', 'trazer', 'tratar', 'transportar', 'transmitir', 'transformar',
                    'trabalhar', 'tornar', 'tomar', 'tocar', 'tirar', 'testar',
                    'terminar', 'ter', 'tentar', 'sustentar', 'suscitar', 'surgir',
                    'suprir', 'suportar', 'sugerir', 'substituir', 'subsistir', 'subsidiar',
                    'subir', 'sorrir', 'sonhar', 'solucionar', 'soltar', 'sobreviver',
                    'significar', 'servir', 'ser', 'separar', 'sentir', 'sentar',
                    'segurar', 'seguir', 'salvar', 'sair', 'saber', 'roubar',
                    'rir', 'rezar', 'rever', 'reunir', 'retornar', 'retirar',
                    'resultar', 'responder', 'respirar', 'respeitar', 'resolver', 'resistir',
                    'residir', 'representar', 'repetir', 'relaxar', 'regressar', 'registrar',
                    'reforçar', 'referir', 'reduzir', 'recusar', 'recuperar', 'recorrer',
                    'reconhecer', 'recolher', 'reclamar', 'receber', 'realizar', 'questionar',
                    'querer', 'queimar', 'quebrar', 'pôr', 'puxar', 'pular',
                    'publicar', 'provocar', 'provar', 'proteger', 'proporcionar', 'propor',
                    'propiciar', 'promover', 'programar', 'produzir', 'procurar', 'prevenir',
                    'prestar', 'preservar', 'preparar', 'preocupar', 'prender', 'preencher',
                    'precisar', 'prazer', 'praticar', 'postar', 'possuir', 'possibilitar',
                    'piorar', 'pintar', 'pesquisar', 'pesar', 'pertencer', 'permitir',
                    'perguntar', 'perdoar', 'perder', 'perceber', 'pensar', 'pegar',
                    'pedir', 'passar', 'partir', 'partilhar', 'participar', 'parlamentar',
                    'parar', 'pagar', 'ouvir', 'originar', 'organizar', 'operar',
                    'olhar', 'oferecer', 'ocupar', 'ocorrer', 'ocasionar', 'obter',
                    'observar', 'notar', 'negociar', 'negar', 'navegar', 'nascer',
                    'mudar', 'mover', 'motivar', 'mostrar', 'morar', 'montar',
                    'militar', 'mexer', 'meter', 'mentir', 'mencionar', 'melhorar',
                    'medir', 'matar', 'marcar', 'manter', 'manifestar', 'mandar',
                    'lutar', 'livrar', 'limpar', 'ligar', 'libertar', 'levar',
                    'levantar', 'ler', 'lembrar', 'lavar', 'largar', 'lançar',
                    'justificar', 'juntar', 'julgar', 'jogar', 'irritar', 'ir',
                    'investir', 'investigar', 'invadir', 'introduzir', 'interpretar', 'integrar',
                    'instigar', 'instalar', 'iniciar', 'informar', 'indicar', 'incomodar',
                    'incluir', 'incentivar', 'impossibilitar', 'impor', 'impedir', 'imaginar',
                    'ignorar', 'identificar', 'haver', 'habitar', 'guardar', 'gravar',
                    'gozar', 'gostar', 'gerar', 'gastar', 'garantir', 'ganhar',
                    'fumar', 'fugir', 'forçar', 'fortalecer', 'fornecer', 'formar',
                    'fomentar', 'focar', 'finalizar', 'ficar', 'fechar', 'fazer',
                    'falar', 'facilitar', 'expressar', 'expor', 'explorar', 'explodir',
                    'explicar', 'expandir', 'existir', 'exigir', 'exercer', 'executar',
                    'evitar', 'estudar', 'estragar', 'estimular', 'estar', 'estabelecer',
                    'esperar', 'espalhar', 'escutar', 'escrever', 'escolher', 'esclarecer',
                    'envolver', 'enviar', 'entregar', 'entrar', 'entender', 'ensinar',
                    'engendrar', 'enganar', 'enfrentar', 'encontrar', 'encher', 'encerrar',
                    'encarar', 'eliminar', 'efetuar', 'editar', 'dormir', 'dizer',
                    'dividir', 'divertir', 'distribuir', 'disponibilizar', 'dispensar', 'discutir',
                    'dirigir', 'diminuir', 'dificultar', 'devolver', 'dever', 'devastar',
                    'determinar', 'deter', 'destruir', 'destacar', 'despertar', 'desligar',
                    'desistir', 'desenvolver', 'desenhar', 'desencadear', 'desejar', 'descrever',
                    'descontinuar', 'descobrir', 'descer', 'descansar', 'derrubar', 'demorar',
                    'demonstrar', 'deixar', 'deitar', 'definir', 'defender', 'dedicar',
                    'declarar', 'decidir', 'dar', 'dançar', 'danificar', 'curar',
                    'cumprir', 'cuidar', 'criticar', 'criar', 'crescer', 'crer',
                    'cortar', 'correr', 'convidar', 'conversar', 'convencer', 'contribuir',
                    'contratar', 'continuar', 'conter', 'contar', 'construir', 'considerar',
                    'conseguir', 'conquistar', 'conhecer', 'confundir', 'confirmar', 'confiar',
                    'conferir', 'conduzir', 'condicionar', 'concorrer', 'concordar', 'concluir',
                    'concentrar', 'comunicar', 'compreender', 'comprar', 'completar', 'competir',
                    'compartilhar', 'comparar', 'começar', 'cometer', 'comer', 'comentar',
                    'combater', 'colocar', 'colher', 'colar', 'cobrir', 'cobrar',
                    'classificar', 'citar', 'circular', 'chorar', 'chegar', 'chamar',
                    'cessar', 'causar', 'casar', 'carregar', 'capturar', 'captar',
                    'capacitar', 'cantar', 'cancelar', 'caminhar', 'calar', 'cair',
                    'buscar', 'brincar', 'bloquear', 'beijar', 'beber', 'bater',
                    'baixar', 'avivar', 'avisar', 'avançar', 'avaliar', 'auxiliar',
                    'aumentar', 'atuar', 'atrair', 'ativar', 'atirar', 'atingir',
                    'atender', 'atacar', 'assumir', 'assistir', 'assinar', 'assegurar',
                    'arrumar', 'arriscar', 'arranjar', 'aproximar', 'aproveitar', 'aprovar',
                    'apresentar', 'aprender', 'apontar', 'apoiar', 'aplicar', 'apertar',
                    'aparecer', 'apanhar', 'apagar', 'anunciar', 'andar', 'analisar',
                    'ampliar', 'amar', 'alterar', 'alimentar', 'alcançar', 'ajudar',
                    'agradecer', 'agir', 'afirmar', 'afetar', 'afastar', 'adquirir',
                    'adotar', 'admitir', 'adicionar', 'adaptar', 'acreditar', 'acordar',
                    'acontecer', 'acompanhar', 'achar', 'aceitar', 'acarretar', 'acalmar',
                    'acabar', 'abrir', 'abandonar'], reverse=True)

time_list = sorted(['afinal', 'ainda', 'antes', 'apenas', 'após', 'atualmente', 'depois', 'enquanto',
                    'finalmente', 'frequentemente', 'mal', 'posteriormente', 'primeiramente', 'quando',
                    'século', 'década', 'ano', 'mês', 'dia', 'período', 'época',
                    'durante', 'meados', 'janeiro', 'fevereiro', 'março', 'abril',
                    'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro',
                    'novembro', 'dezembro'], reverse=True)

conector_causalidade = conector_final + conector_causal
